name: Check Website Uptime
on:
 schedule:
   - cron: '0 * * * *'
   jobs:
 check-uptime:
   runs-on: ubuntu-
   steps:
     - uses: actions/checkout@v4
           - name: Check website status
             run: |
               curl --output /dev/null --silent --head --fail https://eleanorlyj.github.io/
               if [ $? -ne 0 ]; then
                 echo "Website is down"

           echo "Website is up"
         fi
         